### ISSUE TITLE
Error while installing opencv-python on docker container

### ISSUE THREAD

**Issue by Kshitij3003** [prateekralhan/Pic-2-Sketch#1]
Dear Prateek,
I really enjoyed working on this application. But now I am trying to deploy it over a docker container but in doing that I am getting the error in the installation of OpenCV. It would be great if you can assist me in the same.

**Comment by Kshitij3003** [comment]
Bro, I just got the solution from the internet.

Thanks for posting such a wonderful web app.

**Comment by prateekralhan** [comment]
@Kshitij3003 , thank you for the update. Super happy to know that you liked the webapp 😉
